language: node_js
node_js:
  - "8"

services: 
  - postgresql

before_script:
  - psql -c 'create database sneakychattest;' -U postgres

after_script:
  - psql -c 'drop database sneakychattest;' -U postgres